### ISSUE TITLE
Partial copy: only visible text is being copied.

### ISSUE THREAD

**Issue by LiorBanai** [madskristensen/Tweakster#65] opened 2020-11-12 12:40 UTC
I opened an issue regarding copy and it seems there is strange behavior with the extensions:
https://developercommunity.visualstudio.com/content/problem/1246943/visual-studio-copy-only-visible-text-in-editor-wit.html

only visible text is being copied and not the full text selection.
![B353bd576414b4d7a9bc70878c44fc093637407188471529385_vscopy](https://user-images.githubusercontent.com/36262995/98941245-f53d7d80-24f4-11eb-9e86-f91d5150a4a6.gif)

**Comment by PeterOsterdahl** [comment] 2020-11-13 06:32
If you set "Copy without indentiation" to false the problem goes away

**Comment by dizarter** [comment] 2020-12-03 20:46
Duplicate of #62

**Closed** 2020-12-08 16:54 UTC
